// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDIdp-sPealisUAjcmhkDXkZv4xqQRBE',
    appId: '1:265175123695:web:dc1e05db4851e9435dbd1a',
    messagingSenderId: '265175123695',
    projectId: 'wisebite-10665',
    authDomain: 'wisebite-10665.firebaseapp.com',
    storageBucket: 'wisebite-10665.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlLT_XVjaPzgvfXTWKHzkhtoLIkeSML8',
    appId: '1:265175123695:android:6677096f0c0b924c5dbd1a',
    messagingSenderId: '265175123695',
    projectId: 'wisebite-10665',
    storageBucket: 'wisebite-10665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpsRZoOZFvOx3C9PAP43g1-YDKN_L_3is',
    appId: '1:265175123695:ios:d231a3e0bdf5007e5dbd1a',
    messagingSenderId: '265175123695',
    projectId: 'wisebite-10665',
    storageBucket: 'wisebite-10665.firebasestorage.app',
    iosBundleId: 'com.example.wisebite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpsRZoOZFvOx3C9PAP43g1-YDKN_L_3is',
    appId: '1:265175123695:ios:d231a3e0bdf5007e5dbd1a',
    messagingSenderId: '265175123695',
    projectId: 'wisebite-10665',
    storageBucket: 'wisebite-10665.firebasestorage.app',
    iosBundleId: 'com.example.wisebite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTDIdp-sPealisUAjcmhkDXkZv4xqQRBE',
    appId: '1:265175123695:web:646a00e84a6a67e85dbd1a',
    messagingSenderId: '265175123695',
    projectId: 'wisebite-10665',
    authDomain: 'wisebite-10665.firebaseapp.com',
    storageBucket: 'wisebite-10665.firebasestorage.app',
  );
}
